if(${KATIE_PLATFORM} STREQUAL "linux")
    include(generic/generic.cmake)
    include(connman/connman.cmake)
    include(networkmanager/networkmanager.cmake)
elseif(${KATIE_PLATFORM} STREQUAL "win32")
    if(WITH_ICD)
        include(icd/icd.cmake)
    endif()
    # even qt4 didn't build that
    # include(nla/nla.cmake)
    include(generic/generic.cmake)
    if(NOT ${KATIE_PLATFORM} STREQUAL "wince")
        include(nativewifi/nativewifi.cmake)
    endif()
elseif(${KATIE_PLATFORM} STREQUAL "mac")
    include(generic/generic.cmake)
    if(WITH_COREWLAN)
        include(corewlan/corewlan.cmake)
    endif()
elseif(${KATIE_PLATFORM} STREQUAL "blackberry")
    include(blackberry/blackberry.cmake)
else()
    include(generic/generic.cmake)
endif()