set(GUI_HEADERS
    ${GUI_HEADERS}
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qaction.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qaction_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qactiongroup.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qapplication.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qapplication_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qboxlayout.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qclipboard.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qcursor.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qdesktopwidget.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qdrag.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qdnd_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qevent.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qevent_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qformlayout.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qgridlayout.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qkeysequence.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qlayout.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qlayout_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qlayoutengine_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qlayoutitem.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qsessionmanager.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qshortcut.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qshortcutmap_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qsizepolicy.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qpalette.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qstackedlayout.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qtooltip.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwhatsthis.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwidget.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwidget_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwidgetaction.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwidgetaction_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwindowdefs.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qkeymapper_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qgesture.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qgesture_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qstandardgestures_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qgesturerecognizer.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qgesturemanager_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qguiplatformplugin.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qt_x11_p.h
)

set(GUI_SOURCES
    ${GUI_SOURCES}
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qaction.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qactiongroup.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qapplication.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qboxlayout.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qclipboard.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qcursor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qdrag.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qdnd.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qevent.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qformlayout.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qgridlayout.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qkeysequence.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qlayout.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qlayoutengine.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qlayoutitem.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qpalette.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qshortcut.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qshortcutmap.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qstackedlayout.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qtooltip.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qguivariant.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwhatsthis.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwidget.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwidgetaction.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qkeymapper.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qgesture.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qstandardgestures.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qgesturerecognizer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qgesturemanager.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qdesktopwidget.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qguiplatformplugin.cpp
)

if(WITH_X11 AND X11_FOUND)
    set(GUI_HEADERS
        ${GUI_HEADERS}
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qx11embed_x11.h
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qx11info_x11.h
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qeventdispatcher_x11_p.h
    )
    set(GUI_SOURCES
        ${GUI_SOURCES}
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qapplication_x11.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qclipboard_x11.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qcursor_x11.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qdnd_x11.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qdesktopwidget_x11.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qmotifdnd_x11.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwidget_x11.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwidgetcreate_x11.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qx11embed_x11.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qx11info_x11.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qkeymapper_x11.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qeventdispatcher_x11.cpp
    )
    if(WITH_GLIB2 AND GLIB2_FOUND)
        set(GUI_HEADERS
            ${GUI_HEADERS}
            ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qguieventdispatcher_glib_p.h
        )
        set(GUI_SOURCES
            ${GUI_SOURCES}
            ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qguieventdispatcher_glib.cpp
        )
        set(EXTRA_GUI_LIBS
            ${EXTRA_GUI_LIBS}
            ${GLIB2_LIBRARIES}
        )
        include_directories(${GLIB2_INCLUDES})
    endif()
endif()
