set(SQL_HEADERS
    ${SQL_HEADERS}
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qsql.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qsqlquery.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qsqldatabase.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qsqlfield.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qsqlrecord.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qsqldriver.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qsqlnulldriver_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qsqldriverplugin.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qsqlerror.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qsqlresult.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qsqlcachedresult_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qsqlindex.h
)

set(SQL_SOURCES
    ${SQL_SOURCES}
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qsqlquery.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qsqldatabase.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qsqlfield.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qsqlrecord.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qsqldriver.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qsqldriverplugin.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qsqlerror.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qsqlresult.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qsqlindex.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qsqlcachedresult.cpp
)
