=head1 NAME

qcollectiongenerator - part of Qt's Help tool chain

=head1 SYNOPSIS

qcollectiongenerator [options] <collection-config-file>

=head1 DESCRIPTION

TODO

=head1 OPTIONS

    -h
    -help
           Display this information and exit.

    -o <collection-file>
           Generates a collection file called
           <collection-file>. If this option is not
           specified a default name will be used.

    -v
           Displays the version of qcollectiongenerator.

=head1 EXIT STATUS

qcollectiongenerator returns 0 on success and other on unexcepted failure.

=head1 AUTHORS

The Qt Company Ltd.

Copyright (C) 2015 The Qt Company Ltd.

Licensed through GNU Lesser General Public License/GNU General Public License.

=head1 SEE ALSO

qhelpgenerator(1)
