set(GUI_HEADERS
    ${GUI_HEADERS}
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsgridlayout.h
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsitem.h
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsitem_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsitemanimation.h
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicslayout.h
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicslayout_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicslayoutitem.h
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicslayoutitem_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicslinearlayout.h
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsproxywidget.h
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsproxywidget_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsscene.h
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsscene_bsp_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsscene_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsscenebsptreeindex_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicssceneevent.h
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicssceneindex_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsscenelinearindex_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicstransform.h
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicstransform_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsview.h
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsview_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicswidget.h
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicswidget_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgridlayoutengine_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraph_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qsimplex_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsanchorlayout_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsanchorlayout.h
)

set(GUI_SOURCES
    ${GUI_SOURCES}
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsgridlayout.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsitem.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsitemanimation.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicslayout.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicslayout_p.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicslayoutitem.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicslinearlayout.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsproxywidget.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsscene.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsscene_bsp.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsscenebsptreeindex.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicssceneevent.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicssceneindex.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsscenelinearindex.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicstransform.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsview.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicswidget.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicswidget_p.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgridlayoutengine.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qsimplex_p.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsanchorlayout_p.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsanchorlayout.cpp
)
