set(DESIGNER_HEADERS
    ${DESIGNER_HEADERS}
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/shared_global_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/spacer_widget_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/layoutinfo_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/layout_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/connectionedit_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/pluginmanager_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/metadatabase_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_formeditorcommand_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_formwindowcommand_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_command_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/morphmenu_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_command2_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_formbuilder_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_taskmenu_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/formlayoutmenu_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_widget_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_propertysheet_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_membersheet_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_propertyeditor_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_objectinspector_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_integration_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/invisible_widget_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qlayout_widget_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/sheet_delegate_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_stackedbox_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_tabwidget_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_dockwidget_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_toolbox_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_dnditem_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qsimpleresource_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/widgetfactory_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/widgetdatabase_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_promotion_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_introspection_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/promotionmodel_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_promotiondialog_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/iconloader_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/richtexteditor_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/plaintexteditor_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/actioneditor_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/actionrepository_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_toolbar_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_menubar_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_menu_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/actionprovider_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/orderdialog_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/newactiondialog_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/stylesheeteditor_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/csshighlighter_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/shared_enums_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/textpropertyeditor_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/propertylineedit_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/promotiontaskmenu_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/scripterrordialog_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/scriptcommand_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/scriptdialog_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qscripthighlighter_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/gridpanel_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/grid_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/formwindowbase_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_utils_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_widgetbox_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/signalslotdialog_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/extensionfactory_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/dialoggui_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/deviceprofile_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/zoomwidget_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/previewmanager_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/previewconfigurationwidget_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/codedialog_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qtresourceeditordialog_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qtresourcemodel_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qtresourceview_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/iconselector_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/htmlhighlighter_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_widgetitem_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_qsettings_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_formwindowmanager_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/shared_settings_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/newformwidget_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/filterwidget_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/plugindialog_p.h
)

set(DESIGNER_SOURCES
    ${DESIGNER_SOURCES}
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/spacer_widget.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/layoutinfo.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/layout.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/connectionedit.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/pluginmanager.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_formwindowcommand.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_formeditorcommand.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_command.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/morphmenu.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_command2.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_propertycommand.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_formbuilder.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_taskmenu.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/formlayoutmenu.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_widget.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_dockwidget.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_propertysheet.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_membersheet.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_propertyeditor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_objectinspector.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_integration.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_dnditem.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qsimpleresource.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/invisible_widget.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qlayout_widget.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/sheet_delegate.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/metadatabase.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_stackedbox.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_tabwidget.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_toolbox.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/widgetfactory.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/widgetdatabase.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_promotion.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_introspection.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/promotionmodel.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_promotiondialog.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/richtexteditor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/plaintexteditor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/actioneditor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/actionrepository.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_toolbar.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_menubar.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_menu.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/orderdialog.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/newactiondialog.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/stylesheeteditor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/csshighlighter.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/textpropertyeditor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/propertylineedit.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/promotiontaskmenu.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/scripterrordialog.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/scriptcommand.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/scriptdialog.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qscripthighlighter.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/gridpanel.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/grid.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/formwindowbase.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_utils.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_widgetbox.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/iconloader.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/signalslotdialog.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/dialoggui.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/deviceprofile.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/zoomwidget.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/previewmanager.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/previewconfigurationwidget.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/codedialog.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qtresourceeditordialog.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qtresourcemodel.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qtresourceview.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/iconselector.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/htmlhighlighter.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_widgetitem.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_qsettings.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qdesigner_formwindowmanager.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/shared_settings.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/newformwidget.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/filterwidget.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/plugindialog.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/shared.qrc

    ${CMAKE_CURRENT_SOURCE_DIR}/shared/addlinkdialog.ui
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/orderdialog.ui
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/newactiondialog.ui
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/gridpanel.ui
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/signalslotdialog.ui
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/previewconfigurationwidget.ui
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/qtresourceeditordialog.ui
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/newformwidget.ui
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/selectsignaldialog.ui
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/formlayoutrowdialog.ui
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/plugindialog.ui
)

