=head1 NAME

qscript - stand-alone Qt scripts interpreter

=head1 SYNOPSIS

qscript [script-file]

=head1 OPTIONS

    -d
        Attach a debugger.

    -i
        Run interactive.

    -
        Read from standard-input.

=head1 DESCRIPTION

qscript can be used as a stand-alone tool to run Qt scripts which could be
useful when testing. Since the scripts are basically ECMAScript you should see
the ECMA-262 specification for more details about built-in objects, functions
and properties supported.

=head1 EXIT STATUS

qscript returns 0 on success, 1 on wrong usage and other on unexpected
failure.

=head1 AUTHORS

Copyright (C) 2015 The Qt Company Ltd.
Copyright (C) 2016 Ivailo Monev

Licensed through BSD License.
