set(GUI_HEADERS
    ${GUI_HEADERS}
    ${CMAKE_CURRENT_SOURCE_DIR}/math3d/qgenericmatrix.h
    ${CMAKE_CURRENT_SOURCE_DIR}/math3d/qmatrix4x4.h
    ${CMAKE_CURRENT_SOURCE_DIR}/math3d/qquaternion.h
    ${CMAKE_CURRENT_SOURCE_DIR}/math3d/qvector2d.h
    ${CMAKE_CURRENT_SOURCE_DIR}/math3d/qvector3d.h
    ${CMAKE_CURRENT_SOURCE_DIR}/math3d/qvector4d.h
)

set(GUI_SOURCES
    ${GUI_SOURCES}
    ${CMAKE_CURRENT_SOURCE_DIR}/math3d/qgenericmatrix.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/math3d/qmatrix4x4.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/math3d/qquaternion.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/math3d/qvector2d.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/math3d/qvector3d.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/math3d/qvector4d.cpp
)
