set(DESIGNERCOMPONENTS_HEADERS
    ${DESIGNERCOMPONENTS_HEADERS}
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/button_taskmenu.h
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/groupbox_taskmenu.h
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/label_taskmenu.h
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/lineedit_taskmenu.h
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/listwidget_taskmenu.h
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/treewidget_taskmenu.h
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/tablewidget_taskmenu.h
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/combobox_taskmenu.h
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/textedit_taskmenu.h
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/toolbar_taskmenu.h
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/containerwidget_taskmenu.h
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/inplace_editor.h
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/taskmenu_component.h
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/itemlisteditor.h
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/listwidgeteditor.h
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/treewidgeteditor.h
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/tablewidgeteditor.h
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/inplace_widget_helper.h
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/menutaskmenu.h
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/layouttaskmenu.h
)

set(DESIGNERCOMPONENTS_SOURCES
    ${DESIGNERCOMPONENTS_SOURCES}
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/button_taskmenu.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/groupbox_taskmenu.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/label_taskmenu.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/lineedit_taskmenu.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/listwidget_taskmenu.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/treewidget_taskmenu.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/tablewidget_taskmenu.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/combobox_taskmenu.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/textedit_taskmenu.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/toolbar_taskmenu.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/containerwidget_taskmenu.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/inplace_editor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/taskmenu_component.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/itemlisteditor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/listwidgeteditor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/treewidgeteditor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/tablewidgeteditor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/inplace_widget_helper.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/menutaskmenu.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/layouttaskmenu.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/itemlisteditor.ui
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/treewidgeteditor.ui
    ${CMAKE_CURRENT_SOURCE_DIR}/taskmenu/tablewidgeteditor.ui
)

