set(CORE_HEADERS
    ${CORE_HEADERS}
    ${CMAKE_CURRENT_SOURCE_DIR}/codecs/qisciicodec_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/codecs/qlatincodec_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/codecs/qsimplecodec_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/codecs/qtextcodec_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/codecs/qtextcodec.h
    ${CMAKE_CURRENT_SOURCE_DIR}/codecs/qtsciicodec_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/codecs/qutfcodec_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/codecs/qtextcodecplugin.h
)

set(CORE_SOURCES
    ${CORE_SOURCES}
    ${CMAKE_CURRENT_SOURCE_DIR}/codecs/qisciicodec.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/codecs/qlatincodec.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/codecs/qsimplecodec.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/codecs/qtextcodec.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/codecs/qtsciicodec.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/codecs/qutfcodec.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/codecs/qtextcodecplugin.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/codecs/qfontlaocodec.cpp
)

if(WITH_ICONV AND ICONV_FOUND)
    set(CORE_HEADERS
        ${CORE_HEADERS}
        ${CMAKE_CURRENT_SOURCE_DIR}/codecs/qiconvcodec_p.h
    )
    set(CORE_SOURCES
        ${CORE_SOURCES}
        ${CMAKE_CURRENT_SOURCE_DIR}/codecs/qiconvcodec.cpp
    )
    set(EXTRA_CORE_LIBS
        ${EXTRA_CORE_LIBS}
        ${ICONV_LIBRARIES}
    )
    include_directories(${ICONV_INCLUDES})
endif()
