=head1 NAME

lupdate - part of Qt's Linguist tool chain

=head1 SYNOPSIS

lupdate [options] [source-file|path|@lst-file] ... -ts ts-files|@lst-file

=head1 DESCRIPTION

lupdate extracts translatable messages from Qt UI files, C++ and
JavaScript/QtScript source code. Extracted messages are stored in textual
translation source files (typically Qt TS XML). New and modified messages can
be merged into existing TS files.

=head1 OPTIONS

    -h
    -help  Display this information and exit.
    -no-obsolete
           Drop all obsolete strings.

    -extensions <ext>[,<ext>]...
           Process files with the given extensions only.
           The extension list must be separated with commas, not with whitespace.
           Default: 'ui,c,c++,cc,cpp,cxx,ch,h,h++,hh,hpp,hxx,js,qs,qml'.

    -pluralonly
           Only include plural form messages.

    -silent
           Do not explain what is being done.

    -no-sort
           Do not sort contexts in TS files.

    -no-recursive
           Do not recursively scan the following directories.

    -recursive
           Recursively scan the following directories (default).

    -I <includepath> or -I<includepath>
           Additional location to look for include files.
           May be specified multiple times.

    -locations {absolute|relative|none}
           Specify/override how source code references are saved in TS files.
           Default is absolute.
    -no-ui-lines
           Do not record line numbers in references to UI files.

    -disable-heuristic {sametext|similartext|number}
           Disable the named merge heuristic. Can be specified multiple times.

    -source-language <language>[_<region>]
           Specify the language of the source strings for new files.
           Defaults to POSIX if not specified.

    -target-language <language>[_<region>]
           Specify the language of the translations for new files.
           Guessed from the file name if not specified.

    -ts <ts-file>...
           Specify the output file(s). This will override the TRANSLATIONS
           and nullify the CODECFORTR from possibly specified project files.

    -codecfortr <codec>
           Specify the codec assumed for tr() calls. Effective only with -ts.

    -version
           Display the version of lupdate and exit.

    @lst-file
           Read additional file names (one per line) from lst-file.

=head1 EXIT STATUS

lupdate returns 0 on success and other on unexcepted failure.

=head1 AUTHORS

The Qt Company Ltd.

Copyright (C) 2015 The Qt Company Ltd.
Copyright (C) 2016-2019 Ivailo Monev

Licensed through GNU Lesser General Public License/GNU General Public License.

=head1 SEE ALSO

lconvert(1) lrelease(1)
