=head1 NAME

rcc - Katie resource compiler

=head1 SYNOPSIS

rcc [options] <resource-file> [<resource-file>] ...

=head1 DESCRIPTION

TODO

=head1 OPTIONS

    -o <file>
        Write output to file rather than stdout.

    -name <name>
        Create an external initialization function with name.

    -threshold <level>
        Threshold to consider compressing files.

    -compress <level>
        Compress input files by level.

    -root <path>
        Prefix resource access path with root path.

    -no-compress
        Disable all compression.

    -binary
        Output a binary file for use as a dynamic resource.

    -namespace
        Turn off namespace macros.

    -project
        Output a resource file containing all files from the current directory.

    -list
        Lists .qrc file entries.

    -version
        Display version.

    -help
        Display this information.

=head1 EXIT STATUS

rcc returns 0 on success and other on unexcepted failure.

=head1 AUTHORS

Copyright (C) 2015 The Qt Company Ltd.
Copyright (C) 2016 Ivailo Monev

Licensed through GNU Lesser General Public License.
