set(DESIGNER_HEADERS
    ${DESIGNER_HEADERS}
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractformeditor.h
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractintrospection_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractsettings_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractformeditorplugin.h
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractresourcebrowser.h
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractintegration.h
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractpropertyeditor.h
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractformwindow.h
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractformwindowtool.h
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractformwindowcursor.h
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractformwindowmanager.h
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractwidgetdatabase.h
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractmetadatabase.h
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractwidgetfactory.h
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractobjectinspector.h
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractactioneditor.h
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractbrushmanager.h
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstracticoncache.h
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractlanguage.h
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractoptionspage_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/propertysheet.h
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/dynamicpropertysheet.h
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/membersheet.h
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/taskmenu.h
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/extrainfo.h
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractwidgetbox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/layoutdecoration.h
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractdnditem.h
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractpromotioninterface.h
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractdialoggui_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/script_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractnewformwidget_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/sdk_global.h
)

set(DESIGNER_SOURCES
    ${DESIGNER_SOURCES}
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractformeditor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractintrospection.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractformeditorplugin.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractresourcebrowser.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractintegration.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractpropertyeditor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractformwindow.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractformwindowtool.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractformwindowcursor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractformwindowmanager.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractwidgetdatabase.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractmetadatabase.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractwidgetfactory.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractobjectinspector.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractactioneditor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractwidgetbox.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/extrainfo.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractpromotioninterface.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractdialoggui.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/script.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/sdk/abstractnewformwidget.cpp
)
