set(GUI_HEADERS
    ${GUI_HEADERS}
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qabstractitemview.h
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qabstractitemview_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qheaderview.h
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qidentityproxymodel.h
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qlistview.h
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qlistview_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qbsptree_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qtableview.h
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qtableview_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qtreeview.h
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qtreeview_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qabstractitemdelegate.h
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qitemdelegate.h
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qitemselectionmodel.h
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qitemselectionmodel_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qdirmodel.h
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qlistwidget.h
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qlistwidget_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qtablewidget.h
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qtablewidget_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qtreewidget.h
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qtreewidget_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qwidgetitemdata_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qproxymodel.h
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qproxymodel_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qabstractproxymodel.h
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qabstractproxymodel_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qsortfilterproxymodel.h
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qitemeditorfactory.h
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qitemeditorfactory_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qstandarditemmodel.h
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qstandarditemmodel_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qstringlistmodel.h
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qtreewidgetitemiterator.h
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qdatawidgetmapper.h
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qfileiconprovider.h
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qfileiconprovider_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qcolumnviewgrip_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qcolumnview.h 
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qcolumnview_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qstyleditemdelegate.h
)

set(GUI_SOURCES
    ${GUI_SOURCES}
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qabstractitemview.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qheaderview.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qidentityproxymodel.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qlistview.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qbsptree.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qtableview.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qtreeview.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qabstractitemdelegate.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qitemdelegate.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qitemselectionmodel.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qdirmodel.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qlistwidget.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qtablewidget.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qtreewidget.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qproxymodel.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qabstractproxymodel.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qsortfilterproxymodel.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qitemeditorfactory.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qstandarditemmodel.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qstringlistmodel.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qtreewidgetitemiterator.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qdatawidgetmapper.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qfileiconprovider.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qcolumnview.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qcolumnviewgrip.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/itemviews/qstyleditemdelegate.cpp
)
