prefix=${CMAKE_INSTALL_PREFIX}
exec_prefix=${CMAKE_INSTALL_PREFIX}
libdir=${QT_LIBRARIES_PATH}
includedir=${QT_HEADERS_PATH}/${PACKAGE_FAKE}

Name: ${PACKAGE_NAME}
Description: ${PACKAGE_NAME} Library
Version: ${KATIE_VERSION}
Libs: -L${QT_LIBRARIES_PATH} ${PACKAGE_LIBRARIES}
Cflags: ${PACKAGE_CFLAGS} -I${QT_HEADERS_PATH} -I${QT_HEADERS_PATH}/${PACKAGE_FAKE}
Requires: ${PACKAGE_REQUIRES}
