prefix=${KATIE_PREFIX_FULL}
exec_prefix=${KATIE_PREFIX_FULL}
libdir=${KATIE_LIBRARIES_FULL}
includedir=${KATIE_HEADERS_FULL}/${PACKAGE_FAKE}

Name: ${PACKAGE_NAME}
Description: ${PACKAGE_NAME} Library
Version: ${KATIE_VERSION}
Libs: -L${KATIE_LIBRARIES_FULL} -l${PACKAGE_NAME}
Cflags: -I${KATIE_HEADERS_FULL} -I${KATIE_HEADERS_FULL}/${PACKAGE_FAKE} ${PACKAGE_FLAGS}
Requires: ${PACKAGE_REQUIRES}
