prefix=${CMAKE_INSTALL_PREFIX}
exec_prefix=${CMAKE_INSTALL_PREFIX}
libdir=${QT_LIBRARIES_PATH}
includedir=${QT_HEADERS_PATH}/${PACKAGE_FAKE}

Name: ${PACKAGE_NAME}
Description: ${PACKAGE_NAME} Library
Version: ${KATIE_VERSION}
Libs: -L${QT_LIBRARIES_PATH} -l${PACKAGE_NAME}
Cflags: -I${QT_HEADERS_PATH} -I${QT_HEADERS_PATH}/${PACKAGE_FAKE} ${PACKAGE_FLAGS}
Requires: ${PACKAGE_REQUIRES}
