#!/bin/sh

if [ -n "$LD_LIBRARY_PATH" ];then
    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:@KATIE_LIBRARIES_FULL@"
else
    export LD_LIBRARY_PATH="@KATIE_LIBRARIES_FULL@"
fi

if [ -n "$PKG_CONFIG_PATH" ];then
    export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:@KATIE_PKGCONFIG_FULL@"
else
    export PKG_CONFIG_PATH="@KATIE_PKGCONFIG_FULL@"
fi

export Katie_DIR="@KATIE_CMAKE_FULL@"
