set(DESIGNERCOMPONENTS_HEADERS
    ${DESIGNERCOMPONENTS_HEADERS}
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/qdesigner_resource.h
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/qdesignerundostack.h
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/formwindow.h
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/formwindow_widgetstack.h
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/formwindow_dnditem.h
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/formwindowcursor.h
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/widgetselection.h
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/formwindowmanager.h
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/formeditor.h
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/formeditor_global.h
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/qlayoutwidget_propertysheet.h
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/layout_propertysheet.h
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/spacer_propertysheet.h
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/line_propertysheet.h
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/default_container.h
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/default_actionprovider.h
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/qmainwindow_container.h
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/qworkspace_container.h
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/qmdiarea_container.h
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/qwizard_container.h
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/default_layoutdecoration.h
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/qtbrushmanager.h
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/brushmanagerproxy.h
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/iconcache.h
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/tool_widgeteditor.h
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/formeditor_optionspage.h
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/embeddedoptionspage.h
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/formwindowsettings.h
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/deviceprofiledialog.h
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/dpi_chooser.h
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/previewactiongroup.h
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/itemview_propertysheet.h
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/templateoptionspage.h
)

set(DESIGNERCOMPONENTS_SOURCES
    ${DESIGNERCOMPONENTS_SOURCES}
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/deviceprofiledialog.ui
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/formwindowsettings.ui
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/templateoptionspage.ui
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/qdesigner_resource.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/qdesignerundostack.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/formwindow.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/formwindow_widgetstack.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/formwindow_dnditem.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/formwindowcursor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/widgetselection.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/formwindowmanager.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/formeditor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/qlayoutwidget_propertysheet.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/layout_propertysheet.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/spacer_propertysheet.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/line_propertysheet.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/qmainwindow_container.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/qworkspace_container.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/qmdiarea_container.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/qwizard_container.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/default_container.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/default_layoutdecoration.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/default_actionprovider.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/tool_widgeteditor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/qtbrushmanager.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/brushmanagerproxy.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/iconcache.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/formeditor_optionspage.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/embeddedoptionspage.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/formwindowsettings.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/deviceprofiledialog.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/dpi_chooser.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/previewactiongroup.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/itemview_propertysheet.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/templateoptionspage.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/formeditor/formeditor.qrc
)
